<?php
/*
Plugin Name: Custon metabox
Plugin URI: http://wordpress.org/plugins/
Description: This is not just a plugin, 
Author: Aleem
Version: 1.7.1
Author URI: http://ma.tt/
*/


           // how to remove metabox in dashboard section
           // remove_meta_box( // remove_meta_box: this is predefine function 
           // 	"dashboard_quick_press", // this is a metabox id 
           // 	"dashboard",       // is the part/section to show the box
           // 	"side"//  position to show :this is a contant
           // );
           // end remove metabox

    //  generate the online metabox 
    /**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function user_features_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function user_features_add_meta_box() {
	add_meta_box(
		'user_features-user-features',
		__( 'user Features', 'user_features' ),
		'user_features_html',
		'book',
		'side',
		'high'
	);
}
add_action( 'add_meta_boxes', 'user_features_add_meta_box' );

function user_features_html( $post) {
	wp_nonce_field( '_user_features_nonce', 'user_features_nonce' ); ?>

	<p>this is a simple metabox</p>

	<p>
		<label for="user_features_enter_features"><?php _e( 'Enter Features', 'user_features' ); ?></label><br>
		<input type="text" name="user_features_enter_features" id="user_features_enter_features" value="<?php echo user_features_get_meta( 'user_features_enter_features' ); ?>">
	</p><?php
}

function user_features_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['user_features_nonce'] ) || ! wp_verify_nonce( $_POST['user_features_nonce'], '_user_features_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['user_features_enter_features'] ) )
		update_post_meta( $post_id, 'user_features_enter_features', esc_attr( $_POST['user_features_enter_features'] ) );
}
add_action( 'save_post', 'user_features_save' );

/*
	Usage: user_features_get_meta( 'user_features_enter_features' )
*/


    // end generate the online metabox       


    ?>